src/Entity/Home.php
<?php

namespace App\Entity;

use App\Repository\HomeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: HomeRepository::class)]
class Home
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'boolean')]
    private $is_active;

    #[ORM\Column(type: 'string', length: 255)]
    private $titre;

    #[ORM\Column(type: 'string', length: 255)]
    private $texte;

    #[ORM\Column(type: 'string', length: 255)]
    private $image_name;

    #[ORM\Column(type: 'datetime', nullable: true)]
    private $validite_debut;

    #[ORM\Column(type: 'datetime', nullable: true)]
    private $validite_fin;

    #[ORM\Column(type: 'string', length: 255)]
    private $logo;

    #[ORM\OneToMany(mappedBy: 'home', targetEntity: Carousel::class)]
    private $carousels;

    #[ORM\ManyToOne(targetEntity: Faq::class, inversedBy: 'homes')]
    #[ORM\JoinColumn(nullable: false)]
    private $homeFaq;

    public function __construct()
    {
        $this->carousels = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function isIsActive(): ?bool
    {
        return $this->is_active;
    }

    public function setIsActive(bool $is_active): self
    {
        $this->is_active = $is_active;

        return $this;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getTexte(): ?string
    {
        return $this->texte;
    }

    public function setTexte(string $texte): self
    {
        $this->texte = $texte;

        return $this;
    }

    public function getImageName(): ?string
    {
        return $this->image_name;
    }

    public function setImageName(string $image_name): self
    {
        $this->image_name = $image_name;

        return $this;
    }

    public function getValiditeDebut(): ?\DateTimeInterface
    {
        return $this->validite_debut;
    }

    public function setValiditeDebut(?\DateTimeInterface $validite_debut): self
    {
        $this->validite_debut = $validite_debut;

        return $this;
    }

    public function getValiditeFin(): ?\DateTimeInterface
    {
        return $this->validite_fin;
    }

    public function setValiditeFin(?\DateTimeInterface $validite_fin): self
    {
        $this->validite_fin = $validite_fin;

        return $this;
    }

    public function getLogo(): ?string
    {
        return $this->logo;
    }

    public function setLogo(string $logo): self
    {
        $this->logo = $logo;

        return $this;
    }

    /**
     * @return Collection<int, Carousel>
     */
    public function getCarousels(): Collection
    {
        return $this->carousels;
    }

    public function addCarousel(Carousel $carousel): self
    {
        if (!$this->carousels->contains($carousel)) {
            $this->carousels[] = $carousel;
            $carousel->setHome($this);
        }

        return $this;
    }

    public function removeCarousel(Carousel $carousel): self
    {
        if ($this->carousels->removeElement($carousel)) {
            // set the owning side to null (unless already changed)
            if ($carousel->getHome() === $this) {
                $carousel->setHome(null);
            }
        }

        return $this;
    }

    public function getHomeFaq(): ?Faq
    {
        return $this->homeFaq;
    }

    public function setHomeFaq(?Faq $homeFaq): self
    {
        $this->homeFaq = $homeFaq;

        return $this;
    }
}

src/Entity/Mission.php
<?php

namespace App\Entity;

use App\Repository\MissionRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: MissionRepository::class)]
class Mission
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $nom;

    #[ORM\Column(type: 'string', length: 255)]
    private $image_name;

    #[ORM\Column(type: 'text')]
    private $description;

    #[ORM\Column(type: 'string', length: 255)]
    private $type;

    #[ORM\Column(type: 'string', length: 255)]
    private $produit;

    #[ORM\Column(type: 'string', length: 255)]
    private $etat;

    #[ORM\Column(type: 'datetime_immutable')]
    private $updated_at;

    #[ORM\Column(type: 'date')]
    private $date;

    #[ORM\Column(type: 'string', length: 255)]
    private $vehicule;

    #[ORM\Column(type: 'float')]
    private $budget;

    #[ORM\Column(type: 'float')]
    private $latitude;

    #[ORM\Column(type: 'float')]
    private $longitude;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getImageName(): ?string
    {
        return $this->image_name;
    }

    public function setImageName(string $image_name): self
    {
        $this->image_name = $image_name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getProduit(): ?string
    {
        return $this->produit;
    }

    public function setProduit(string $produit): self
    {
        $this->produit = $produit;

        return $this;
    }

    public function getEtat(): ?string
    {
        return $this->etat;
    }

    public function setEtat(string $etat): self
    {
        $this->etat = $etat;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeImmutable $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getVehicule(): ?string
    {
        return $this->vehicule;
    }

    public function setVehicule(string $vehicule): self
    {
        $this->vehicule = $vehicule;

        return $this;
    }

    public function getBudget(): ?float
    {
        return $this->budget;
    }

    public function setBudget(float $budget): self
    {
        $this->budget = $budget;

        return $this;
    }

    public function getLatitude(): ?float
    {
        return $this->latitude;
    }

    public function setLatitude(float $latitude): self
    {
        $this->latitude = $latitude;

        return $this;
    }

    public function getLongitude(): ?float
    {
        return $this->longitude;
    }

    public function setLongitude(float $longitude): self
    {
        $this->longitude = $longitude;

        return $this;
    }
}

src/Controller/AdminCategorieController.php
<?php

namespace App\Controller;

use App\Entity\Categorie;
use App\Form\CategorieType;
use App\Repository\CategorieRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/admin/categorie')]
class AdminCategorieController extends AbstractController
{
    #[Route('/', name: 'app_admin_categorie_index', methods: ['GET'])]
    public function index(CategorieRepository $categorieRepository): Response
    {
        return $this->render('admin_categorie/index.html.twig', [
            'categories' => $categorieRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_admin_categorie_new', methods: ['GET', 'POST'])]
    public function new(Request $request, CategorieRepository $categorieRepository): Response
    {
        $categorie = new Categorie();
        $form = $this->createForm(CategorieType::class, $categorie);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $categorieRepository->add($categorie, true);

            return $this->redirectToRoute('app_admin_categorie_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('admin_categorie/new.html.twig', [
            'categorie' => $categorie,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_admin_categorie_show', methods: ['GET'])]
    public function show(Categorie $categorie): Response
    {
        return $this->render('admin_categorie/show.html.twig', [
            'categorie' => $categorie,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_admin_categorie_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Categorie $categorie, CategorieRepository $categorieRepository): Response
    {
        $form = $this->createForm(CategorieType::class, $categorie);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $categorieRepository->add($categorie, true);

            return $this->redirectToRoute('app_admin_categorie_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('admin_categorie/edit.html.twig', [
            'categorie' => $categorie,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_admin_categorie_delete', methods: ['POST'])]
    public function delete(Request $request, Categorie $categorie, CategorieRepository $categorieRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$categorie->getId(), $request->request->get('_token'))) {
            $categorieRepository->remove($categorie, true);
        }

        return $this->redirectToRoute('app_admin_categorie_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/admin_categorie/_delete_form.html.twig
<form method="post" action="{{ path('app_admin_categorie_delete', {'id': categorie.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ categorie.id) }}">
    <button class="btn btn-danger">Delete</button>
</form>

templates/admin_categorie/edit.html.twig
{% extends 'base-backend.html.twig' %}
{% block title %}Edit Categorie{% endblock %}

{% block body %}
    <h1>Edit Categorie</h1>

    {{ include('admin_categorie/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_admin_categorie_index') }}">Retour à la liste</a>

    {{ include('admin_categorie/_delete_form.html.twig') }}
{% endblock %}

templates/admin_categorie/index.html.twig
{% extends 'base-backend.html.twig' %}
{% block title %}Categories{% endblock %}

{% block body %}
<div class="container-fluid">
    <h1>Categories</h1>
    <a href="{{ path('app_admin_categorie_new') }}" class="btn btn-dark">Nouveau</a>


    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom</th>
                <th>Slug</th>
                <th>Image_name</th>
                {# <th>Updated_at</th> #}
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for categorie in categories %}
            <tr>
                <td>{{ categorie.id }}</td>
                <td>{{ categorie.nom }}</td>
                <td>{{ categorie.slug }}</td>
                <td>{{ categorie.imageName }}</td>

                {# <td>{{ categorie.updatedAt ? categorie.updatedAt|date('Y-m-d H:i:s') : '' }}</td> #}
                <td>
                    <a href="{{ path('app_admin_categorie_show', {'id': categorie.id}) }}" class= "btn btn-dark">Afficher</a>
                    <a href="{{ path('app_admin_categorie_edit', {'id': categorie.id}) }}" class= "btn btn-dark">Modifier</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">Aucun enregistrement</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    </div>

{% endblock %}

templates/admin_categorie/new.html.twig
{% extends 'base-backend.html.twig' %}
{% block title %}Nouvelle Categorie{% endblock %}

{% block body %}
    <h1>Nouvelle Categorie</h1>

    {{ include('admin_categorie/_form.html.twig') }}

    <a href="{{ path('app_admin_categorie_index') }}">Retour à la liste</a>
{% endblock %}

templates/admin_categorie/show.html.twig
{% extends 'base-backend.html.twig' %}
{% block title %}Categorie{% endblock %}

{% block body %}
    <h1>Categorie</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ categorie.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ categorie.nom }}</td>
            </tr>
            <tr>
                <th>Slug</th>
                <td>{{ categorie.slug }}</td>
            </tr>
            <tr>
                <th>Image_name</th>
                <td>{{ categorie.imageName }}</td>
            </tr>
            <tr>
                <th>Updated_at</th>
                <td>{{ categorie.updatedAt ? categorie.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_admin_categorie_index') }}">Retour à la liste</a>

    <a href="{{ path('app_admin_categorie_edit', {'id': categorie.id}) }}"class= "btn btn-dark">Modifier</a>

    {{ include('admin_categorie/_delete_form.html.twig') }}
{% endblock %}