src/Entity/Home.php
<?php

namespace App\Entity;

use App\Repository\HomeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: HomeRepository::class)]
class Home
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'boolean')]
    private $is_active;

    #[ORM\Column(type: 'string', length: 255)]
    private $titre;

    #[ORM\Column(type: 'string', length: 255)]
    private $texte;

    #[ORM\Column(type: 'string', length: 255)]
    private $image_name;

    #[ORM\Column(type: 'datetime', nullable: true)]
    private $validite_debut;

    #[ORM\Column(type: 'datetime', nullable: true)]
    private $validite_fin;

    #[ORM\Column(type: 'string', length: 255)]
    private $logo;

    #[ORM\OneToMany(mappedBy: 'home', targetEntity: Carousel::class)]
    private $carousels;

    #[ORM\ManyToOne(targetEntity: Faq::class, inversedBy: 'homes')]
    #[ORM\JoinColumn(nullable: false)]
    private $homeFaq;

    public function __construct()
    {
        $this->carousels = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function isIsActive(): ?bool
    {
        return $this->is_active;
    }

    public function setIsActive(bool $is_active): self
    {
        $this->is_active = $is_active;

        return $this;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getTexte(): ?string
    {
        return $this->texte;
    }

    public function setTexte(string $texte): self
    {
        $this->texte = $texte;

        return $this;
    }

    public function getImageName(): ?string
    {
        return $this->image_name;
    }

    public function setImageName(string $image_name): self
    {
        $this->image_name = $image_name;

        return $this;
    }

    public function getValiditeDebut(): ?\DateTimeInterface
    {
        return $this->validite_debut;
    }

    public function setValiditeDebut(?\DateTimeInterface $validite_debut): self
    {
        $this->validite_debut = $validite_debut;

        return $this;
    }

    public function getValiditeFin(): ?\DateTimeInterface
    {
        return $this->validite_fin;
    }

    public function setValiditeFin(?\DateTimeInterface $validite_fin): self
    {
        $this->validite_fin = $validite_fin;

        return $this;
    }

    public function getLogo(): ?string
    {
        return $this->logo;
    }

    public function setLogo(string $logo): self
    {
        $this->logo = $logo;

        return $this;
    }

    /**
     * @return Collection<int, Carousel>
     */
    public function getCarousels(): Collection
    {
        return $this->carousels;
    }

    public function addCarousel(Carousel $carousel): self
    {
        if (!$this->carousels->contains($carousel)) {
            $this->carousels[] = $carousel;
            $carousel->setHome($this);
        }

        return $this;
    }

    public function removeCarousel(Carousel $carousel): self
    {
        if ($this->carousels->removeElement($carousel)) {
            // set the owning side to null (unless already changed)
            if ($carousel->getHome() === $this) {
                $carousel->setHome(null);
            }
        }

        return $this;
    }

    public function getHomeFaq(): ?Faq
    {
        return $this->homeFaq;
    }

    public function setHomeFaq(?Faq $homeFaq): self
    {
        $this->homeFaq = $homeFaq;

        return $this;
    }
}

src/Controller/AdminHomeController.php
<?php

namespace App\Controller;

use App\Entity\Home;
use App\Form\HomeType;
use App\Repository\HomeRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/admin/home')]
class AdminHomeController extends AbstractController
{
    #[Route('/', name: 'app_admin_home_index', methods: ['GET'])]
    public function index(HomeRepository $homeRepository): Response
    {
        return $this->render('admin_home/index.html.twig', [
            'homes' => $homeRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_admin_home_new', methods: ['GET', 'POST'])]
    public function new(Request $request, HomeRepository $homeRepository): Response
    {
        $home = new Home();
        $form = $this->createForm(HomeType::class, $home);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $homeRepository->add($home, true);

            return $this->redirectToRoute('app_admin_home_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('admin_home/new.html.twig', [
            'home' => $home,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_admin_home_show', methods: ['GET'])]
    public function show(Home $home): Response
    {
        return $this->render('admin_home/show.html.twig', [
            'home' => $home,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_admin_home_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Home $home, HomeRepository $homeRepository): Response
    {
        $form = $this->createForm(HomeType::class, $home);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $homeRepository->add($home, true);

            return $this->redirectToRoute('app_admin_home_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('admin_home/edit.html.twig', [
            'home' => $home,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_admin_home_delete', methods: ['POST'])]
    public function delete(Request $request, Home $home, HomeRepository $homeRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$home->getId(), $request->request->get('_token'))) {
            $homeRepository->remove($home, true);
        }

        return $this->redirectToRoute('app_admin_home_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/admin_home/_delete_form.html.twig
<form method="post" action="{{ path('app_admin_home_delete', {'id': home.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ home.id) }}">
    <button class= "btn btn-danger">Supprimer</button>
</form>

templates/admin_home/edit.html.twig
{% extends 'base-backend.html.twig' %}

{% block title %}Edit Home{% endblock %}

{% block body %}
    <h1>Edit Home</h1>

    {{ include('admin_home/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_admin_home_index') }}">Retour à la liste</a>

    {{ include('admin_home/_delete_form.html.twig') }}
{% endblock %}

templates/admin_home/index.html.twig
{% extends 'base-backend.html.twig' %}

{% block title %}Home{% endblock %}

{% block body %}
<div class="container-fluid">
    <h1>Home</h1>
    <a href="{{ path('app_admin_home_new') }}" class="btn btn-dark">Nouveau</a>


    <table class="table">
        <thead>
            <tr>
                {# <th>Id</th> #}
                <th>Is_active</th>
                <th>Titre</th>
                <th>Texte</th>
                <th>Image_name</th>
                <th>Validite_debut</th>
                <th>Validite_fin</th>
                <th>Logo</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for home in homes %}
            <tr>
                {# <td>{{ home.id }}</td> #}
                <td>{{ home.isActive ? 'Yes' : 'No' }}</td>
                <td>{{ home.titre }}</td>
                <td>{{ home.texte }}</td>
                <td>{{ home.imageName }}</td>
                <td>{{ home.validiteDebut ? home.validiteDebut|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ home.validiteFin ? home.validiteFin|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ home.logo }}</td>
            
                <td>
                    <a href="{{ path('app_admin_home_show', {'id': home.id}) }}" class= "btn btn-dark">Afficher</a>
                    <a href="{{ path('app_admin_home_edit', {'id': home.id}) }}" class= "btn btn-dark">Modifier</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="9">Aucun enregistrement</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    </div>

{% endblock %}

templates/admin_home/new.html.twig
{% extends 'base-backend.html.twig' %}

{% block title %}New Home{% endblock %}

{% block body %}
    <h1>Nouveau Home</h1>

    {{ include('admin_home/_form.html.twig') }}

    <a href="{{ path('app_admin_home_index') }}">Retour à la liste</a>
{% endblock %}

templates/admin_home/show.html.twig
{% extends 'base-backend.html.twig' %}

{% block title %}Home{% endblock %}

{% block body %}
    <h1>Home</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ home.id }}</td>
            </tr>
            <tr>
                <th>Is_active</th>
                <td>{{ home.isActive ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Titre</th>
                <td>{{ home.titre }}</td>
            </tr>
            <tr>
                <th>Texte</th>
                <td>{{ home.texte }}</td>
            </tr>
            <tr>
                <th>Image_name</th>
                <td>{{ home.imageName }}</td>
            </tr>
            <tr>
                <th>Validite_debut</th>
                <td>{{ home.validiteDebut ? home.validiteDebut|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Validite_fin</th>
                <td>{{ home.validiteFin ? home.validiteFin|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Logo</th>
                <td>{{ home.logo }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_admin_home_index') }}">Retour à la liste</a>

    <a href="{{ path('app_admin_home_edit', {'id': home.id}) }}"class= "btn btn-dark">Modifier</a>

    {{ include('admin_home/_delete_form.html.twig') }}
{% endblock %}